version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    networks:
      - app_network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  backend:
    image: cooperjsk/backend:latest
    container_name: backend
    restart: always
    networks:
      - app_network
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017"
      NODE_ENV: production
      PORT: 3000
      FRONTEND_URL: "http://frontend:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - ./Backend:/home/node/app
      - /home/node/app/node_modules

  frontend:
    image: cooperjsk/frontend:latest
    container_name: frontend
    restart: always
    networks:
      - app_network
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3000
      - PORT=5000

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data: